### ISSUE TITLE
`config.json` file not present in repository

### ISSUE THREAD

**Issue by SpicyRicecaker** [NovaSagittarii/catan-realtime#1]
Attempting to run the game after `npm i` with `npm start` results in the following error message:
```
node:fs:584
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './config.json' 
    at Object.openSync (node:fs:584:3)
    at Object.readFileSync (node:fs:452:35)
    at file:///C:/Users/[...]/catan-realtime/index.js:15:30
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './config.json'
}
```

**Comment by SpicyRicecaker** [comment]
Commenting line https://github.com/NovaSagittarii/catan-realtime/blob/665e06eb10dcf82e0a4addc5a6ca9e42637aac37/index.js#L15
and adding `60` to https://github.com/NovaSagittarii/catan-realtime/blob/665e06eb10dcf82e0a4addc5a6ca9e42637aac37/index.js#L66 fixes it, but I wonder what else is in the `config.json`?

**Comment by NovaSagittarii** [comment]
wait im trolling, i had *.json in gitignore and forgot about my config.json XD
